name: Updating Atlantis' MySql database

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Perform git pull
      run: git pull origin master

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: atlantis_database
        environment-file: environment.yml
        python-version: 3.10

    - name: Verify Conda environment
      run: conda info

    - name: Run asynchronous_db.py script
      run: python asynchronous_db.py
